service: notifier

provider:
  name: aws
  runtime: python3.8
  profile: pythonAutomation
  region: eu-west-2

custom:
  snsTopicName: ${self:service}-sns
  snsTopic: arn:aws:sns:${self:provider.region}:${self:custom.accountid}:${self:custom.snsTopicName}
  accountid: xxx #supply AWS Account ID
  email: xxx #supply email address for SNS messages
  ASG: xxx #supply Auto Scaling Group

functions:
  notifier:
    handler: handler.notifier
    iamRoleStatements:
      - Effect: Allow
        Action: sns:Publish
        Resource: ${self:custom.snsTopic}
    destinations:
      onSuccess: ${self:custom.snsTopic}
    environment:
      SNSTopic: ${self:custom.snsTopic}
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.autoscaling"
            detail-type:
              - "EC2 Instance Launch Successful"
            detail:
              AutoScalingGroupName:
                - ${self:custom.ASG}
resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.snsTopicName}
    SNSSub:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${self:custom.email}
        Protocol: email
        TopicArn: {"Ref": "SNSTopic"}

